### ISSUE TITLE
A few more details...

### ISSUE THREAD

**Issue by mikblack** [GenomicsAotearoa/methods-and-musings#6]
Hi Christina,
Thanks for submitting this.  Can you put a few more details into the document to provide some background/context for others who are interested in this information?
Once this has been done, I'll add a link to your document to the main Methods and Musing README.md.
Thanks
Mik

**Comment by christinawu2008** [comment]
Hi Mik,
I have put a bit more details there, hopefully enough to get people informed. More details will be put there time by time. I think people working on GA high-quality genomes are all welcome to contribute, will think more about how. But I'll start mine.
Thanks!
Chen
